name: Java CI with Gradle

on: [push, workflow_dispatch]

jobs:
  build-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew publish
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    - name: Upload artifacts
      uses: rexlmanu/pterodactyl-upload-action@v1
      with:
        panel-host: ${{ secrets.PANEL_HOST }}
        api-key: ${{ secrets.API_KEY }}
        server-id: "8936a2f6"
        restart: "true"
        source: "proxy/build/libs/velocity-proxy-3.2.0-SNAPSHOT-all.jar"
        target: "./velocity.jar"
